name: Cypress Tests on Ubuntu
on:
  push:
    branches:
      - 'master'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.2' 
      - run: npm ci
      - name: Run Tests
        run: npm run test:chrome
      - name: Generate Report
        if: always()
        run: npm run allure:generate             
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: ./allure-report
      - name: Push to another branch
        if: always()
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: reports 
          FOLDER: ./allure-report 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          MESSAGE: "Reports added" 